version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: devserver
    container_name: crypto-webpack
    volumes:
      - ./src:/app/src
    ports:
      - 3000:80

  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: crypto-production
    ports:
      - 8080:80